// <auto-generated />
using System;
using DicomApp.DAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DicomApp.DAL.Migrations
{
    [DbContext(typeof(ShippingDBContext))]
    [Migration("20241130152031_cleanUpDB")]
    partial class cleanUpDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DicomApp.DAL.DB.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance");

                    b.Property<string>("Ban")
                        .HasColumnName("BAN");

                    b.Property<string>("BankName");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Iban")
                        .HasColumnName("IBAN");

                    b.Property<string>("InstaPay");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("RefId")
                        .HasMaxLength(100);

                    b.Property<int?>("RoleId");

                    b.Property<int>("UserId");

                    b.Property<int?>("VodafoneCash");

                    b.HasKey("AccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdvertisementRequestId");

                    b.Property<int?>("BuyerId");

                    b.Property<int?>("CashTransferId");

                    b.Property<int?>("CommonUserId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int>("GameId");

                    b.Property<int?>("GameId1");

                    b.Property<int>("GamerId");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRefund");

                    b.Property<DateTime?>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<int>("Level");

                    b.Property<int>("OldPrice");

                    b.Property<string>("Password")
                        .HasMaxLength(250);

                    b.Property<int>("Price");

                    b.Property<string>("Rank");

                    b.Property<string>("RefId")
                        .HasMaxLength(255);

                    b.Property<int>("StatusId");

                    b.Property<string>("UserName")
                        .HasMaxLength(500);

                    b.HasKey("AdvertisementId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CommonUserId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("GamerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Advertisement");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.AdvertisementPhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvertisementId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("AdvertisementPhotos");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.AppService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowAnonymous");

                    b.Property<bool>("AllowLog");

                    b.Property<string>("ClassName")
                        .HasMaxLength(150);

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LogMessage")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool?>("ShowToUser")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("Service_Name_unique");

                    b.ToTable("AppService");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy");

                    b.Property<int?>("DeleteBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnName("Name_Ar")
                        .HasMaxLength(150);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnName("Name_En")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.CommonResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(150);

                    b.Property<int?>("ModifiedBy");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ResourceLang")
                        .HasMaxLength(5);

                    b.Property<string>("ResourceValue")
                        .IsRequired();

                    b.Property<string>("Url")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("ResourceKey", "ResourceLang")
                        .IsUnique()
                        .HasName("IX_Common_Resource")
                        .HasFilter("[ResourceKey] IS NOT NULL AND [ResourceLang] IS NOT NULL");

                    b.ToTable("Common_Resource");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.CommonUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .HasMaxLength(150);

                    b.Property<int?>("AccountNumber");

                    b.Property<string>("Address")
                        .HasMaxLength(150);

                    b.Property<string>("AddressDetails")
                        .HasMaxLength(150);

                    b.Property<int>("Age");

                    b.Property<int?>("Apartment");

                    b.Property<int?>("AreaId");

                    b.Property<int?>("Averageorders");

                    b.Property<string>("Bank")
                        .HasMaxLength(150);

                    b.Property<int?>("BranchId");

                    b.Property<string>("Code")
                        .HasMaxLength(50);

                    b.Property<bool>("ConfirmEmail");

                    b.Property<int?>("CountryId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("Floor");

                    b.Property<string>("FullName")
                        .HasMaxLength(100);

                    b.Property<int>("Gender");

                    b.Property<string>("HashedPassword");

                    b.Property<int?>("IbanNumber")
                        .HasColumnName("IBAN_Number");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("InstaPayAccountName")
                        .HasMaxLength(150);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsLoggedIn");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Landmark");

                    b.Property<string>("Language");

                    b.Property<DateTime?>("LastLocationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Lat")
                        .HasMaxLength(50);

                    b.Property<string>("Lng")
                        .HasMaxLength(50);

                    b.Property<string>("LocationUrl");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool?>("OpenPackage");

                    b.Property<string>("PageName")
                        .HasMaxLength(100);

                    b.Property<bool?>("PartialDelivery");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ProductType")
                        .HasMaxLength(100);

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID");

                    b.Property<string>("TelegramUserName");

                    b.Property<long?>("VerificationCode");

                    b.Property<bool?>("VisaPayment");

                    b.Property<int?>("WalletNumber");

                    b.Property<int?>("ZoneId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("RoleId");

                    b.ToTable("CommonUser");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.CommonUserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AuthCreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("AuthExpirationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AuthIp")
                        .HasColumnName("AuthIP")
                        .HasMaxLength(100);

                    b.Property<string>("AuthToken")
                        .HasMaxLength(250);

                    b.Property<int>("CommonUserId")
                        .HasColumnName("Common_UserID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DeviceEmail")
                        .HasMaxLength(150);

                    b.Property<string>("DeviceImei")
                        .HasColumnName("DeviceIMEI")
                        .HasMaxLength(150);

                    b.Property<string>("DeviceMobileNumber")
                        .HasMaxLength(50);

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("DeviceOsversion")
                        .HasColumnName("DeviceOSVersion")
                        .HasMaxLength(150);

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(500);

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool?>("EnableNotification")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool?>("IsGoogleSupport");

                    b.Property<bool>("IsLoggedIn");

                    b.Property<string>("Lang")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ModifiedBy");

                    b.HasKey("Id");

                    b.HasIndex("CommonUserId");

                    b.ToTable("Common_UserDevice");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("FlagUrl");

                    b.Property<string>("NameAr");

                    b.Property<string>("NameEn");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionType");

                    b.Property<int?>("AdvertisementId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy");

                    b.Property<int>("EntityType");

                    b.Property<int?>("GamerServiceId");

                    b.Property<string>("Message");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GamerServiceId");

                    b.ToTable("FollowUp");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy");

                    b.Property<int?>("DeleteBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("ImgUrl")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnName("Name_Ar")
                        .HasMaxLength(150);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnName("Name_En")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.GameCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("CreatedBy");

                    b.Property<int?>("DeleteBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int>("Discount");

                    b.Property<int>("GameId");

                    b.Property<string>("Img");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameCharges");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.GamerService", b =>
                {
                    b.Property<int>("GamerServiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<string>("CurrentLevel");

                    b.Property<string>("Description");

                    b.Property<int?>("GameChargeId");

                    b.Property<int>("GameId");

                    b.Property<int>("GameServiceType");

                    b.Property<int>("GamerId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<string>("Level");

                    b.Property<string>("Password");

                    b.Property<int>("Price");

                    b.Property<string>("RefId");

                    b.Property<int>("StatusId");

                    b.Property<string>("UserName");

                    b.HasKey("GamerServiceId");

                    b.HasIndex("GameChargeId");

                    b.HasIndex("GameId");

                    b.HasIndex("GamerId");

                    b.HasIndex("StatusId");

                    b.ToTable("GamerService");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdvertisementId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<int?>("GamerServiceId");

                    b.Property<int>("InvoiceType");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRefund");

                    b.Property<DateTime?>("LastModifiedAt");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<int>("Price");

                    b.Property<string>("RefId");

                    b.HasKey("InvoiceId");

                    b.HasIndex("AdvertisementId")
                        .IsUnique()
                        .HasFilter("[AdvertisementId] IS NOT NULL");

                    b.HasIndex("GamerServiceId")
                        .IsUnique()
                        .HasFilter("[GamerServiceId] IS NOT NULL");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NotificationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Icon")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDeleted");

                    b.Property<bool?>("IsSeen");

                    b.Property<int?>("RecipientId")
                        .HasColumnName("RecipientID");

                    b.Property<int?>("RecipientRoleId");

                    b.Property<int?>("SeenBy");

                    b.Property<DateTime?>("SeenDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("SenderId")
                        .HasColumnName("SenderID");

                    b.Property<string>("TargetPath");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientRoleId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteAt");

                    b.Property<int?>("DeleteBy");

                    b.Property<bool>("Editable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.RoleAppService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppServiceId")
                        .HasColumnName("AppServiceID");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("Enabled");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ModifiedBy");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AppServiceId", "RoleId")
                        .IsUnique()
                        .HasName("RoleIDServiceIDUniq");

                    b.ToTable("RoleAppService");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameAR")
                        .HasMaxLength(50);

                    b.Property<string>("NameEN")
                        .HasMaxLength(50);

                    b.Property<int>("StatusType");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Testimonial", b =>
                {
                    b.Property<int>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatedBy");

                    b.Property<int?>("DeleteBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastModifiedAt");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<int?>("LastModifiedByNavigationId");

                    b.Property<int>("Rate");

                    b.HasKey("TestimonialId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedByNavigationId");

                    b.ToTable("Testimonial");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId");

                    b.Property<int?>("AccountId1");

                    b.Property<int?>("AccountId2");

                    b.Property<int?>("AdvertisementId");

                    b.Property<int>("Amount");

                    b.Property<string>("Attachment");

                    b.Property<int>("BuyerId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSuccess");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<string>("PaymentId");

                    b.Property<string>("RefId")
                        .HasMaxLength(100);

                    b.Property<int?>("ServiceId");

                    b.Property<int>("TransactionSource");

                    b.Property<int>("TransactionType");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId1");

                    b.HasIndex("AccountId2");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedBy");

                    b.HasIndex("ServiceId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.UserLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(250);

                    b.Property<long>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ApplicationID")
                        .HasDefaultValueSql("((1))");

                    b.Property<double?>("AquirityDistance")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("BataryStatus");

                    b.Property<long?>("ChannelId")
                        .HasColumnName("ChannelID");

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<double?>("DirectionAngle")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250);

                    b.Property<bool?>("IsOnline")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<int?>("NetworkStatus");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnName("PlaceID")
                        .HasMaxLength(250);

                    b.Property<DateTime>("SubmitDateTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(250);

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLocation");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Userhubconnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnName("ConnectionID")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsOnline");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ModifiedBy");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Userhubconnection");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Account", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.CommonUser", "CreatedByNavigation")
                        .WithMany("AccountCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Account_CommonUser1");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "LastModifiedByNavigation")
                        .WithMany("AccountLastModifiedByNavigation")
                        .HasForeignKey("LastModifiedBy")
                        .HasConstraintName("FK_Account_CommonUser2");

                    b.HasOne("DicomApp.DAL.DB.Role", "Role")
                        .WithMany("Account")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Account_Role");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "User")
                        .WithMany("AccountUser")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Account_CommonUser");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Advertisement", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.CommonUser", "Buyer")
                        .WithMany("AdvertisementsBuyer")
                        .HasForeignKey("BuyerId");

                    b.HasOne("DicomApp.DAL.DB.CommonUser")
                        .WithMany("ShipmentCustomer")
                        .HasForeignKey("CommonUserId");

                    b.HasOne("DicomApp.DAL.DB.Game", "Game")
                        .WithMany("Advertisements")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK_Shipment_Game")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DicomApp.DAL.DB.Game")
                        .WithMany("ShipmentWarehouseGame")
                        .HasForeignKey("GameId1");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "Gamer")
                        .WithMany("AdvertisementsGamer")
                        .HasForeignKey("GamerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DicomApp.DAL.DB.Status", "Status")
                        .WithMany("Advertisements")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DicomApp.DAL.DB.AdvertisementPhotos", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Advertisement", "Advertisement")
                        .WithMany("AdvertisementPhotos")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DicomApp.DAL.DB.CommonUser", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");

                    b.HasOne("DicomApp.DAL.DB.Role", "Role")
                        .WithMany("CommonUser")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_CommonUser_Role");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.CommonUserDevice", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.CommonUser", "CommonUser")
                        .WithMany("CommonUserDevice")
                        .HasForeignKey("CommonUserId")
                        .HasConstraintName("FK_Common_UserDevice_Common_User");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.ContactUs", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.CommonUser", "User")
                        .WithMany("ContactUs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ContactUs_CommonUser");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.FollowUp", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Advertisement", "Advertisement")
                        .WithMany("FollowUp")
                        .HasForeignKey("AdvertisementId")
                        .HasConstraintName("FK_FollowUp_Shipment");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "CreatedByNavigation")
                        .WithMany("FollowUp")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Visit_FollowUp_CommonUser");

                    b.HasOne("DicomApp.DAL.DB.GamerService")
                        .WithMany("FollowUp")
                        .HasForeignKey("GamerServiceId");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Game", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Category", "Category")
                        .WithMany("Game")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Game_Category");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.GameCharge", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Game", "Game")
                        .WithMany("GameCharges")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DicomApp.DAL.DB.GamerService", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.GameCharge", "GameCharge")
                        .WithMany("GamerServices")
                        .HasForeignKey("GameChargeId");

                    b.HasOne("DicomApp.DAL.DB.Game", "Game")
                        .WithMany("GamerServices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "Gamer")
                        .WithMany("GamerServices")
                        .HasForeignKey("GamerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DicomApp.DAL.DB.Status", "Status")
                        .WithMany("GamerServices")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Invoice", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Advertisement", "Advertisement")
                        .WithOne("Invoice")
                        .HasForeignKey("DicomApp.DAL.DB.Invoice", "AdvertisementId");

                    b.HasOne("DicomApp.DAL.DB.GamerService", "GamerService")
                        .WithOne("Invoice")
                        .HasForeignKey("DicomApp.DAL.DB.Invoice", "GamerServiceId");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Notification", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Role", "RecipientRole")
                        .WithMany("Notification")
                        .HasForeignKey("RecipientRoleId")
                        .HasConstraintName("FK_Notification_Notification1");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "Sender")
                        .WithMany("Notification")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Notification_Notification");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.RoleAppService", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.AppService", "AppService")
                        .WithMany("RoleAppService")
                        .HasForeignKey("AppServiceId")
                        .HasConstraintName("FK_RoleAppService_AppService");

                    b.HasOne("DicomApp.DAL.DB.Role", "Role")
                        .WithMany("RoleAppService")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RoleAppService_Role1");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Testimonial", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.CommonUser", "CreatedByNavigation")
                        .WithMany("Testimonials")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "LastModifiedByNavigation")
                        .WithMany()
                        .HasForeignKey("LastModifiedByNavigationId");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.Transaction", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.Account")
                        .WithMany("AccountTransactionReceiver")
                        .HasForeignKey("AccountId");

                    b.HasOne("DicomApp.DAL.DB.Account")
                        .WithMany("AccountTransactionSender")
                        .HasForeignKey("AccountId1");

                    b.HasOne("DicomApp.DAL.DB.Account")
                        .WithMany("AccountTransactionVendor")
                        .HasForeignKey("AccountId2");

                    b.HasOne("DicomApp.DAL.DB.Advertisement", "Advertisement")
                        .WithMany("Transactions")
                        .HasForeignKey("AdvertisementId");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "CreatedByNavigation")
                        .WithMany("AccountTransactionCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_AccountTransaction_CommonUser");

                    b.HasOne("DicomApp.DAL.DB.CommonUser", "LastModifiedByNavigation")
                        .WithMany("AccountTransactionLastModifiedByNavigation")
                        .HasForeignKey("LastModifiedBy")
                        .HasConstraintName("FK_AccountTransaction_CommonUser1");

                    b.HasOne("DicomApp.DAL.DB.GamerService", "Service")
                        .WithMany("Transactions")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("DicomApp.DAL.DB.UserLocation", b =>
                {
                    b.HasOne("DicomApp.DAL.DB.CommonUser", "User")
                        .WithMany("UserLocation")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserLocation_Common_User");
                });
#pragma warning restore 612, 618
        }
    }
}
